name: CI-Build

on:
  push:
    branches: 
    - master
    - "**"
  pull_request:
    branches: 
    - master

jobs:

  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    - name: Install Linux packages
      run: sudo apt update && sudo apt install -y --no-install-recommends libgtk-3-0 libgtk-3-dev libpango-1.0-0 libpango1.0-dev libpangocairo-1.0-0
      
    - name: Set up Go 1.16
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
        
    - name: Get Gtk version and the environment
      run: pkg-config --modversion gtk+-3.0;env

    - name: Caching build artifacts and modules
      uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-modules-${{ hashFiles('**/go.sum') }}

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Build
      run: go build -v -ldflags "-X main.version=$GITHUB_SHA" .

    - name: Test
      run: go test -v -timeout=30s ./...
      
    - name: 'Upload binary for linux_x86_64'
      uses: actions/upload-artifact@v2
      with:
        name: hellocontest-binary
        path: ./hellocontest
