name: Release-Build

on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-22.04
    outputs:
      version_number: ${{ steps.version_number.outputs.version_number }}
      package_name: ${{ steps.package_filename.outputs.package_filename }}
    steps:
    - name: Install Linux packages
      run: sudo apt update && sudo apt install -y --no-install-recommends libgtk-3-0 libgtk-3-dev libpango-1.0-0 libpango1.0-dev libpangocairo-1.0-0
      
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Set up Go 1.20
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
      id: go

    - name: Get Gtk version and the environment
      run: |
        pkg-config --modversion gtk+-3.0
        env

    - name: Version Number
      id: version_number
      run: echo "version_number=$(make version_number)" >> $GITHUB_OUTPUT
          
    - name: Show Version
      run: echo "Version ${{ steps.version_number.outputs.version_number }}"

    - name: Build
      run: make deps test build

    - name: Create package structure
      run: |
        mkdir -p ./.debpkg/usr/bin
        cp ./hellocontest ./.debpkg/usr/bin/hellocontest
        chmod +x ./.debpkg/usr/bin/hellocontest

    - name: Create deb package
      run: make debpkg

    - id: package_filename
      run: echo "package_filename=$(ls ./hellocontest*.deb | head -n 1)" >> $GITHUB_OUTPUT

    - name: 'Upload package for linux_x86_64'
      uses: actions/upload-artifact@v3
      with:
        name: hellocontest-package
        path: ./hellocontest*.deb

    - name: Upload package to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ steps.package_filename.outputs.package_filename }}
        tag: ${{ github.ref }}
